WEB_Assignment_Team2/Models/Competition.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WEB_Assignment_Team2.Models
{
    public class Competition
    {
        [Display(Name ="Competition ID")]
        public int CompetitionID { get; set; }
        [Display(Name ="Area of Interest ID")]
        public int AreaInterestID { get; set; }
        [Display(Name ="Competition Name")]
        [StringLength(255, ErrorMessage = "Name of competition cannot be more than 255 characters.")]
        [Required(ErrorMessage = "Please enter a name.")]
        public string CompetitionName { get; set; }
        [Display(Name ="Start Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0: d-MMM-yyyy}")]
        public DateTime? StartDate { get; set; }
        [Display(Name ="End Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString ="{0: d-MMM-yyyy}")]
        public DateTime? EndDate { get; set; }
        [Display(Name ="Result Released Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0: d-MMM-yyyy}")]
        public DateTime? ResultReleasedDate { get; set; }
    }
}

WEB_Assignment_Team2/Models/CompetitionJudge.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WEB_Assignment_Team2.Models
{
    public class CompetitionJudge
    {
        [Display(Name ="Competition ID")]
        public int CompetitionID { get; set; }
        [Display(Name ="Judge ID")]
        public int JudgeID { get; set; }
    }
}

WEB_Assignment_Team2/Models/CompetitionJudgeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WEB_Assignment_Team2.Models
{
    public class CompetitionJudgeViewModel
    {
        public Competition SelectedCompetition { get; set; }
        public List<Judge> JudgeList { get; set; }
    }
}

WEB_Assignment_Team2/Models/CompetitionViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WEB_Assignment_Team2.Models
{
    public class CompetitionViewModel
    {
        public List<Competition> ListCompetition { get; set; }
        public List<AreaInterest> AiList { get; set; }
        public CompetitionJudgeViewModel CompJudgeVM { get; set; }
    }
}

WEB_Assignment_Team2/Controllers/CompetitionController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WEB_Assignment_Team2.DAL;
using WEB_Assignment_Team2.Models;

namespace WEB_Assignment_Team2.Controllers
{
    public class CompetitionController : Controller
    {
        private AreaInterestDAL aiContext = new AreaInterestDAL();
        private CompetitionDAL competitionContext = new CompetitionDAL();
        private CompetitorDAL competitorContext = new CompetitorDAL();
        private CompetitionJudgeDAL compJudgeContext = new CompetitionJudgeDAL();
        private CompetitionSubmissionDAL competitionSubmissionCOntext = new CompetitionSubmissionDAL();
        private CriteriaDAL criteriaContext = new CriteriaDAL();
        private JudgeDAL judgeContext = new JudgeDAL();
        public ActionResult MyCompetition()
        {
            //Authenticate user session state
            if ((HttpContext.Session.GetString("Role") == "judge" &&
            HttpContext.Session.GetString("JudgeID") != null))
            {
                List<CompetitionJudge> listcompjudge = compJudgeContext.GetAllCompetition(Convert.ToInt32(HttpContext.Session.GetString("JudgeID")));
                List<Competition> listCompetition = new List<Competition>();
                //get all competition details from database
                foreach (CompetitionJudge cj in listcompjudge)
                {
                    listCompetition.Add(competitionContext.GetCompetition(cj.CompetitionID));
                }
                //Prepare model to be sent to view
                CompetitionViewModel compList = new CompetitionViewModel
                {
                    ListCompetition = listCompetition,
                    AiList = aiContext.GetAllAreaInterest(),
                };
                return View(compList);
            }
            else if ((HttpContext.Session.GetString("Role") != null) &&
            (HttpContext.Session.GetString("Role") == "competitor"))
            {
                // Getting all the competitions the user has joined
                CompetitionViewModel compList = new CompetitionViewModel
                {
                    ListCompetition = competitionContext.GetJoinedCompetition(Convert.ToInt32(HttpContext.Session.GetString("CompetitorID"))),
                    AiList = aiContext.GetAllAreaInterest(),
                };
                return View(compList);
            }
            else
            {
                return RedirectToAction("index", "home");
            }
        }
        public ActionResult AllCompetitions()
        {
            // gets all the competitions in the database
            CompetitionViewModel compList = new CompetitionViewModel
            {
                ListCompetition = competitionContext.GetAllCompetition(),
                AiList = aiContext.GetAllAreaInterest(),
            };
            return View(compList);
        }

        // view all competitions and judges assigned
        public ActionResult CompetitionJudges(int? id)
        {
            if ((HttpContext.Session.GetString("Role") == null) ||
            (HttpContext.Session.GetString("Role") != "admin"))
            {
                return RedirectToAction("index", "home");
            }
            CompetitionViewModel compList = new CompetitionViewModel
            {
                ListCompetition = competitionContext.GetAllCompetition(),
                AiList = aiContext.GetAllAreaInterest(),
            };
            ViewData["selComp"] = "";
            if (id != null)
            {
                CompetitionJudgeViewModel compjudge = new CompetitionJudgeViewModel
                {
                    SelectedCompetition = competitionContext.GetCompetition(id.Value),
                    JudgeList = judgeContext.GetJudgeInCompetition(id.Value),
                };
                //check if after end date of competition
                if (DateTime.Now > compjudge.SelectedCompetition.EndDate)
                {
                    // Display manage judges error message
                    TempData["CompJudgeError"] = "Competition have ended, unable to manage judges.";
                    return View(compList);
                }
                //display message according to number of judges assigned to competition
                if (compjudge.JudgeList.Count == 0)
                    TempData["CompJudgeError"] = "There are currently no judges assigned to " + compjudge.SelectedCompetition.CompetitionName + ". Please assign at least two judges!";
                else
                    TempData["CompJudgeSuccess"] = "Judges in " + compjudge.SelectedCompetition.CompetitionName + " have been displayed.";
                ViewData["selComp"] = id.Value;
                compList.CompJudgeVM = compjudge;
            }
            return View(compList);
        }

        public ActionResult CompetitionRanking()
        {
            CompetitionViewModel compList = new CompetitionViewModel
            {
                ListCompetition = competitionContext.GetAllCompetition(),
                AiList = aiContext.GetAllAreaInterest(),
            };
            return View(compList);
        }
        public ActionResult JoinCompetition(int competitionID)
        {
            // adds an empty submission into competition table
            // makes competitor join the competition
            if ((HttpContext.Session.GetString("Role") == "competitor" &&
            HttpContext.Session.GetString("CompetitorID") != null))
            {
                Competition c = competitionContext.GetCompetition(competitionID);
                if (c != null)
                {
                    if (c.StartDate > DateTime.Now.AddDays(3))
                    {
                        competitionSubmissionCOntext.AddCompetitionSubmission(competitionID, Convert.ToInt32(HttpContext.Session.GetString("CompetitorID")));
                    }

                }
                
            }
            return RedirectToAction("View", "Criteria", new { id = competitionID });
        }

        public ActionResult CreateCompetition()
        {
            if ((HttpContext.Session.GetString("Role") == null) ||
            (HttpContext.Session.GetString("Role") != "admin"))
            {
                return RedirectToAction("index", "home");
            }
            // Get list of AreaInterest to display as dropdown list
            ViewData["AIList"] = GetAllAI();
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateCompetition(Competition competition)
        {
            // Get AreaInterest list in case need to return to CreateCompetition page
            ViewData["AIList"] = GetAllAI();
            if (ModelState.IsValid)
            {
                // check start and end dates of competition
                if (competition.StartDate > competition.EndDate)
                {
                    TempData["CCError"] = "Competition start date cannot be later than end date!";
                    return View(competition);
                }
                // check end and result release dates of competition
                if (competition.EndDate >= competition.ResultReleasedDate)
                {
                    TempData["CCError"] = "Competition end date cannot be later than result released date!";
                    return View(competition);
                }
                competition.CompetitionID = competitionContext.AddCompetition(competition);
                // Display create competition success message
                TempData["CompSuccess"] = "New Competition successfully created!";
                return RedirectToAction("AllCompetitions");
            }
            else
            {
                return View(competition);
            }
        }
        public ActionResult EditCompetition(int? id)
        {
            if ((HttpContext.Session.GetString("Role") == null) ||
            (HttpContext.Session.GetString("Role") != "admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null)
            { 
                return RedirectToAction("AllCompetitions");
            }
            bool compExist = competitionContext.IsCompetitorExist(id.Value);
            if (compExist == true) //competitor records found
            {
                // Display edit competition error message
                TempData["CompError"] = "There are competitor records found, competition cannot be edited.";
                return RedirectToAction("AllCompetitions");
            }
            ViewData["AIList"] = GetAllAI();
            Competition competition = competitionContext.GetCompetition(id.Value);
            if (competition == null)
            {
                // Return to listing page, not allowed to edit
                return RedirectToAction("AllCompetitions");
            }
            return View(competition);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditCompetition(Competition competition)
        {
            ViewData["AIList"] = GetAllAI();
            if (ModelState.IsValid)
            {
                // check start and end dates of competition
                if (competition.StartDate > competition.EndDate)
                {
                    TempData["ECError"] = "Competition start date cannot be later than end date!";
                    return View(competition);
                }
                // check end and result release dates of competition
                if (competition.EndDate >= competition.ResultReleasedDate)
                {
                    TempData["ECError"] = "Competition end date cannot be the same or later than result released date!";
                    return View(competition);
                }

WEB_Assignment_Team2/Views/Competition/AllCompetitions.cshtml
@model WEB_Assignment_Team2.Models.CompetitionViewModel
@{
    ViewData["Title"] = "All Competitions";
}
<div id="comp-container" class="container">
    @{if (Context.Session.GetString("Role") == "competitor")
        {
            <h2>Join Competitions</h2>
            <br />
            @foreach (var item in Model.ListCompetition)
            {
                <div class="form-container" style="margin-bottom: 20px;" onclick="location.href = '@Url.Action("View", "Criteria", new {id=item.CompetitionID})'">
                    <p>
                        <div>
                            <b>@Html.DisplayFor(modelItem => item.CompetitionName)</b> <br />
                        </div>
                        <div style="margin-top:10px;">
                            Competition Dates: <br />
                            @Html.DisplayFor(modelItem => item.StartDate) to @Html.DisplayFor(modelItem => item.EndDate) <br />
                        </div>
                        <div style="margin-top:10px;">
                            Results Release Date: <br />
                            @Html.DisplayFor(modelItem => item.ResultReleasedDate)
                        </div>
                    </p>
                    <span>
                        <span class="btn" style="color:#FD7F02;border-color:black;border-radius:1000px;">
                            @Html.DisplayFor(model => model.AiList.Find(a => a.AreaInterestID == item.AreaInterestID).Name)
                        </span>
                    </span>
                </div>
            }
        }
        else if (Context.Session.GetString("Role") == "admin")
        {
            <h2>View Competitions</h2>
            <div style="color:forestgreen">@TempData["CompSuccess"]</div>
            <div style="color:orangered">@TempData["CompError"]</div> <br />
            <a asp-action="CreateCompetition"
               class="btn" style="color:#FD7F02;border-color:black;border-radius:1000px;margin-bottom: 20px;">Create New Competition</a>
            <br />
            foreach (var item in Model.ListCompetition)
            {
                <div class="form-container" style="margin-bottom: 20px;">
                    <p>
                        <div>
                            <b>@Html.DisplayFor(modelItem => item.CompetitionName)</b> <br />
                        </div>
                        <div style="margin-top:10px;">
                            Area of Interest: <br />
                            @Html.DisplayFor(model => model.AiList.Find(a => a.AreaInterestID == item.AreaInterestID).Name)
                        </div>
                        <div style="margin-top:10px;">
                            Competition Dates: <br />
                            @Html.DisplayFor(modelItem => item.StartDate) to @Html.DisplayFor(modelItem => item.EndDate) <br />
                        </div>
                        <div style="margin-top:10px;">
                            Results Release Date: <br />
                            @Html.DisplayFor(modelItem => item.ResultReleasedDate)
                        </div>
                    </p>
                    <span>
                        <a asp-action="EditCompetition" asp-controller="Competition"
                           asp-route-id="@item.CompetitionID"
                           class="btn" style="color:#FD7F02;border-color:black;border-radius:1000px;">Edit</a>
                        <a asp-action="DeleteCompetition" asp-controller="Competition"
                           asp-route-id="@item.CompetitionID"
                           class="btn" style="color:#FD7F02;border-color:black;border-radius:1000px;">Delete</a>
                    </span>
                </div>
            }
        }

        else if (Context.Session.GetString("Role") == null)
        {
            <h2>View Competitions</h2>
            <br />
            foreach (var item in Model.ListCompetition)
            {
                <div class="form-container" style="margin-bottom: 20px; cursor:pointer;" onclick="location.href = '@Url.Action("viewdetails", "submission", new {id=item.CompetitionID})'">
                    <p>
                        <div>
                            <b>@Html.DisplayFor(modelItem => item.CompetitionName)</b> <br />
                        </div>
                        <div style="margin-top:10px;">
                            Area of Interest: <br />
                            @Html.DisplayFor(model => model.AiList.Find(a => a.AreaInterestID == item.AreaInterestID).Name)
                        </div>
                        <div style="margin-top:10px;">
                            Competition Dates: <br />
                            @Html.DisplayFor(modelItem => item.StartDate) to @Html.DisplayFor(modelItem => item.EndDate) <br />
                        </div>
                        <div style="margin-top:10px;">
                            Results Release Date: <br />
                            @Html.DisplayFor(modelItem => item.ResultReleasedDate)
                        </div>
                    </p>
                    <span>
                        <span class="btn" style="color:#FD7F02;border-color:black;border-radius:1000px;">@Html.ActionLink("View Competition Details", "viewdetails", "submission", new { id = item.CompetitionID })</span>
                    </span>
                </div>
            }
        }
    }
</div>

WEB_Assignment_Team2/Views/Competition/CompetitionJudges.cshtml
@model WEB_Assignment_Team2.Models.CompetitionViewModel
@{
    ViewData["Title"] = "Competition Judges";
}
<div id="comp-container" class="container">
    <h2>Judges for Competitions</h2>
    <div style="color:forestgreen">@TempData["CompJudgeSuccess"]</div>
    <div style="color:orangered">@TempData["CompJudgeError"]</div>
    <br />
    @foreach (var item in Model.ListCompetition)
    {
        <div class="form-container" style="margin-bottom: 20px;">
            <p>
                <div>
                    <b>@Html.DisplayFor(modelItem => item.CompetitionName)</b> <br />
                </div>
                <div style="margin-top:10px;">
                    Area of Interest: <br />
                    @Html.DisplayFor(model => model.AiList.Find(a => a.AreaInterestID == item.AreaInterestID).Name)
                </div>
                <div style="margin-top:10px;">
                    Competition Dates: <br />
                    @Html.DisplayFor(modelItem => item.StartDate) to @Html.DisplayFor(modelItem => item.EndDate) <br />
                </div>
                <div style="margin-top:10px;">
                    Results Release Date: <br />
                    @Html.DisplayFor(modelItem => item.ResultReleasedDate)
                </div>
            </p>
            <span>
                <a asp-action="CompetitionJudges"
                    asp-route-id="@item.CompetitionID"
                    class="btn" style="color:#FD7F02;border-color:black;border-radius:1000px;">Manage Judges</a>
            </span>
            <!-- display table with judges in competition-->
            @if (ViewData["selComp"].ToString() != "" && Model.CompJudgeVM.SelectedCompetition.CompetitionID == item.CompetitionID)
            {
                <hr />
                <span>
                    <a asp-action="AssignJudge" asp-controller="Judge"
                        asp-route-id="@item.CompetitionID"
                        class="btn" style="color:#FD7F02;border-color:black;border-radius:1000px;margin-bottom:20px;">Assign New Judge</a>
                </span>
                <br />
                if (Model.CompJudgeVM.JudgeList.Count != 0)
                {
                <div class="table-responsive">
                    <table id="viewCompJudge" class="table table-striped table-bordered">
                        <thead class="thead-dark">
                            <tr>
                                <th>ID</th>
                                <th>Judge Name</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach (var judge in Model.CompJudgeVM.JudgeList)
                        {
                            if (Model.CompJudgeVM.JudgeList.Count <= 2)
                            {
                                <tr>
                                <td>@Html.DisplayFor(modelItem => judge.JudgeID)</td>
                                <td>@Html.DisplayFor(modelItem => judge.Salutation) @Html.DisplayFor(modelItem => judge.JudgeName)</td>
                                <td></td>
                            </tr>
                            }
                            else
                            {
                                <tr>
                                <td>@Html.DisplayFor(modelItem => judge.JudgeID)</td>
                                <td>@Html.DisplayFor(modelItem => judge.Salutation) @Html.DisplayFor(modelItem => judge.JudgeName)</td>
                                <td>
                                    <a asp-action="RemoveJudge" asp-controller="Judge"
                                        asp-route-id="@judge.JudgeID"
                                        class="btn" style="color:#FD7F02;">Remove Judge</a>
                                </td>
                            </tr>
                            }
                        }
                        </tbody>
                    </table>
                </div>
                }
                else
                {
                    <p style="color:orangered">
                        There are currently no judges assigned to this competition. Please assign at least 2 judges!
                    </p>
                }
            }
        </div>
    }
</div>

WEB_Assignment_Team2/Views/Competition/CompetitionRanking.cshtml
@model WEB_Assignment_Team2.Models.CompetitionViewModel
@{
    ViewData["Title"] = "Competition Ranking";
}
<div id="comp-container" class="container">
    <h2>View Rankings</h2>
    <br />
    @foreach (var item in Model.ListCompetition)
    {
        <div class="form-container" style="margin-bottom: 20px;">
            <p>
                <div>
                    <b>@Html.DisplayFor(modelItem => item.CompetitionName)</b> <br />
                </div>
                <div style="margin-top:10px;">
                    Area of Interest: <br />
                    @Html.DisplayFor(model => model.AiList.Find(a => a.AreaInterestID == item.AreaInterestID).Name)
                </div>
                <div style="margin-top:10px;">
                    Competition Dates: <br />
                    @Html.DisplayFor(modelItem => item.StartDate) to @Html.DisplayFor(modelItem => item.EndDate) <br />
                </div>
                <div style="margin-top:10px;">
                    Results Release Date: <br />
                    @Html.DisplayFor(modelItem => item.ResultReleasedDate)
                </div>
            </p>
            <span>
                <span class="btn" style="color:#FD7F02;border-color:black;border-radius:1000px;">@Html.ActionLink("View Rankings", "PublicRankView", "Rank", new { id = item.CompetitionID })</span>
            </span>
        </div>
    }
</div>

WEB_Assignment_Team2/Views/Competition/CreateCompetition.cshtml
@model WEB_Assignment_Team2.Models.Competition
@{
    ViewData["Title"] = "Create Competition";
}
<div id="comp-container" class="container">
    <h2>Create New Competition</h2>
    <div style="color:orangered">@TempData["CCError"]</div> <br />
    <form asp-action="CreateCompetition">
        <fieldset class="FormContent form-container" style="margin-bottom: 20px;">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CompetitionName" class="control-label"></label>
                <input asp-for="CompetitionName" class="form-control" />
                <span asp-validation-for="CompetitionName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AreaInterestID" class="control-label"></label>
                <select asp-for="AreaInterestID"
                        asp-items="@(new SelectList( @ViewData["AIList"]
                                    as List <AreaInterest>, "AreaInterestID", "Name"))"
                        class="form-control"></select>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ResultReleasedDate" class="control-label"></label>
                <input asp-for="ResultReleasedDate" class="form-control" />
                <span asp-validation-for="ResultReleasedDate" class="text-danger"></span>
            </div>
            <div class="row form-group">
                <div style="padding:15px;">
                    <input type="submit" value="Create" class="btn btn-success" />
                </div>
                <div style="padding:15px;">
                    <input asp-action="AllCompetitions" type="submit" value="Cancel" class="btn btn-danger" />
                </div>
            </div>
        </fieldset>
    </form>
</div>

WEB_Assignment_Team2/Views/Competition/EditCompetition.cshtml
@model WEB_Assignment_Team2.Models.Competition
@{
    ViewData["Title"] = "Edit Competition";
}
<div id="comp-container" class="container">
    <h2>Edit Competition</h2>
    <div style="color:orangered">@TempData["ECError"]</div> <br />
    <form asp-action="EditCompetition">
        <fieldset class="FormContent form-container" style="margin-bottom: 20px;">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CompetitionID" class="control-label"></label>
                <input asp-for="CompetitionID" readonly class="form-control" />
                <span asp-validation-for="CompetitionID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AreaInterestID" class="control-label"></label>
                <select asp-for="AreaInterestID"
                        asp-items="@(new SelectList( @ViewData["AIList"]
                                    as List <AreaInterest>, "AreaInterestID", "Name"))"
                        class="form-control"></select>
            </div>
            <div class="form-group">
                <label asp-for="CompetitionName" class="control-label"></label>
                <input asp-for="CompetitionName" class="form-control" />
                <span asp-validation-for="CompetitionName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ResultReleasedDate" class="control-label"></label>
                <input asp-for="ResultReleasedDate" class="form-control" />
                <span asp-validation-for="ResultReleasedDate" class="text-danger"></span>
            </div>
            <div class="row form-group">
                <div style="padding:15px;">
                    <input type="submit" value="Save" class="btn btn-success" />
                </div>
                <div style="padding:15px;">
                    <input asp-action="AllCompetitions" type="submit" value="Cancel" class="btn btn-danger" />
                </div>
            </div>
        </fieldset>
    </form>
</div>