WEB_Assignment_Team2/Models/AreaInterest.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WEB_Assignment_Team2.Models
{
    public class AreaInterest
    {
        public int AreaInterestID { get; set; }

        [Display(Name="Name of Area of Interest")]
        [StringLength(50,ErrorMessage ="Name of area of interest cannot be more than 50 characters.")]
        [Required(ErrorMessage ="Please enter a name.")]
        [ValidateAINameExists]
        public string Name { get; set; }
    }
}

WEB_Assignment_Team2/Controllers/AreaInterestController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WEB_Assignment_Team2.DAL;
using WEB_Assignment_Team2.Models;

namespace WEB_Assignment_Team2.Controllers
{
    public class AreaInterestController : Controller
    {
        private AreaInterestDAL aiContext = new AreaInterestDAL();
        public ActionResult Index()
        {
            if (HttpContext.Session.GetString("Role") != "admin")
            {
                return RedirectToAction("index", "home");
            }
            List<AreaInterest> aiList = aiContext.GetAllAreaInterest();
            return View(aiList);
        }

        public ActionResult Create()
        {
            if (HttpContext.Session.GetString("Role") != "admin")
            {
                return RedirectToAction("index", "home");
            }
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AreaInterest areaInterest)
        {
            if (ModelState.IsValid)
            {
                areaInterest.AreaInterestID = aiContext.AddAI(areaInterest);
                // Display create area of interest success message
                TempData["AIsuccess"] = "New Area of Interest successfully created!";
                return RedirectToAction("Index");
            }
            else
            {
                return View(areaInterest);
            }
        }

        public ActionResult Delete(int? id)
        {
            if (HttpContext.Session.GetString("Role") != "admin")
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            // Check conditions before deleting
            bool compExist = aiContext.IsCompetitionExist(id.Value);
            bool judgeExist = aiContext.IsJudgeExist(id.Value);
            if (compExist == true) //competition records found
            {
                // Display delete area of interest error message
                TempData["AIdeleteError"] = "There are competition records found, Area of Interest cannot be deleted.";
                return RedirectToAction("Index");
            }
            if (judgeExist == true) //judge records found
            {
                // Display delete area of interest error message
                TempData["AIdeleteError"] = "There are judge records found, Area of Interest cannot be deleted.";
                return RedirectToAction("Index");
            }
            else //no issues, can delete
            {
                aiContext.Delete(id.Value);
                // Display delete area of interest success message
                TempData["AIsuccess"] = "Area of Interest successfully deleted!";
                return RedirectToAction("Index");
            }
        }
    }
}

WEB_Assignment_Team2/Views/AreaInterest/Create.cshtml
@model WEB_Assignment_Team2.Models.AreaInterest
@{
    ViewData["Title"] = "Create Area Of Interest";
}
<div id="ai-container" class="container">
    <h2>Create New Area of Interest</h2><br />
    <form asp-action="Create">
        <fieldset class="FormContent form-container" style="margin-bottom: 20px;">
            <div class="form-group">
                <label asp-for="Name"></label>
                <div>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            <div class="row form-group">
                <div style="padding:15px;">
                    <input type="submit" value="Create" class="btn btn-success" />
                </div>
                <div style="padding:15px;">
                    <input asp-action="Index" type="submit" value="Cancel" class="btn btn-danger" />
                </div>
            </div>
        </fieldset>
    </form>
</div>

WEB_Assignment_Team2/Views/AreaInterest/Index.cshtml
@model IEnumerable<WEB_Assignment_Team2.Models.AreaInterest>
@{
    ViewData["Title"] = "View Area Of Interest";
}
<partial name="~/Views/AreaInterest/_ViewAI.cshtml" model="@Model" />

WEB_Assignment_Team2/Views/AreaInterest/_ViewAI.cshtml
@model IEnumerable<WEB_Assignment_Team2.Models.AreaInterest>

@if (Model.ToList().Count > 0)
{
<div id="ai-container" class="container">
    <h2>View Area of Interest</h2>
    <div style="color:forestgreen">@TempData["AIsuccess"]</div>
    <div style="color:orangered">@TempData["AIdeleteError"]</div> <br />
    <a asp-action="Create" 
       class="btn" style="color:#FD7F02;border-color:black;border-radius:1000px;margin-bottom: 20px;">Create New Area of Interest</a>
    <br />
    @foreach (var item in Model)
    {
        <div class="form-container" style="margin-bottom: 20px;">
            <p>
                <div>
                    <b>@item.Name</b><br />
                </div>
                <div style="margin-top:10px;">
                    Area of Interest ID: @item.AreaInterestID
                </div>
            </p>
            <span>
                <a asp-action="Delete" asp-controller="AreaInterest"
                   asp-route-id="@item.AreaInterestID"
                   class="btn" style="color:#FD7F02;border-color:black;border-radius:1000px;">Delete</a>
            </span>
        </div>
    }
</div>
}
else
{
    <span style="color:red">No record found!</span>
}