WEB_Assignment_Team2/Models/Judge.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WEB_Assignment_Team2.Models
{
    public class Judge
    {
        [Display(Name = "Judge ID")]
        public int JudgeID { get; set; }
        [Display(Name = "Judge Name")]
        [Required(ErrorMessage ="Please enter your name.")]
        [StringLength(50,ErrorMessage ="Name cannot exceed 50 characters.")]
        public string JudgeName { get; set; }
        public string Salutation { get; set; }
        [Display(Name ="Area of Interest")]
        [Required(ErrorMessage = "Please enter your area of interest.")]
        public int AreaInterestID { get; set; }
        [Display(Name = "Email Address")]
        [RegularExpression(@"[A-Za-z0-9._%+-]+@lcu.edu.sg")]
        [StringLength(50, ErrorMessage = "Email cannot exceed 50 characters.")]
        [Required(ErrorMessage = "Please enter your email.")]
        public string EmailAddr { get; set; }
        [Display(Name ="Password")]
        [StringLength(255,ErrorMessage ="Password cannot exceed 255 characters.")]
        public string Password { get; set; }
    }
}

WEB_Assignment_Team2/Controllers/JudgeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using WEB_Assignment_Team2.DAL;
using WEB_Assignment_Team2.Models;

namespace WEB_Assignment_Team2.Controllers
{
    public class JudgeController : Controller
    {
        private JudgeDAL judgeContext = new JudgeDAL();
        private AreaInterestDAL aiContext = new AreaInterestDAL();
        private CompetitionSubmissionDAL compSubmissionContext = new CompetitionSubmissionDAL();
        private CompetitionDAL competitionContext = new CompetitionDAL();
        private CompetitionJudgeDAL compJudgeContext = new CompetitionJudgeDAL();


        private void SetAOI(Competition c)
        {
            List<AreaInterest> ailist = aiContext.GetAllAreaInterest();
            ViewData["AreaOfInterest"] = ailist.Find(a => a.AreaInterestID == c.AreaInterestID).Name;
        }
        public ActionResult View(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("MyCompetition", "Competition");
            }
            CompetitionJudgeViewModel cc = new CompetitionJudgeViewModel
            {
                SelectedCompetition = competitionContext.GetCompetition(id.Value),
                JudgeList = judgeContext.GetJudgeInCompetition(id.Value),
            };
            // Check whether competition exists
            if (cc.SelectedCompetition == null)
            {
                return RedirectToAction("MyCompetition", "Competition");
            }
            // Set up Area of Interest in _CompetitionDetails
            SetAOI(cc.SelectedCompetition);

            if ((HttpContext.Session.GetString("Role") != null) &&
            (HttpContext.Session.GetString("Role") == "competitor"))
            {
                // checks whether competitor has joined competition, and if join button needs to be shown
                if (compSubmissionContext.IsJoined(Convert.ToInt32(HttpContext.Session.GetString("CompetitorID")), id.Value))
                {
                    ViewData["DisplayJoinButton"] = false;
                }
                else
                {
                    ViewData["DisplayJoinButton"] = true;
                }
                return View(cc);
            }
            else if (HttpContext.Session.GetString("Role") == "judge")
            {
                return View(cc);
            }
            else
            {
                return RedirectToAction("index", "home");
            }
        }

        // assign judge to selected competition 
        public ActionResult AssignJudge(int? id)
        {
            CompetitionJudgeViewModel compjudge = new CompetitionJudgeViewModel
            {
                SelectedCompetition = competitionContext.GetCompetition(id.Value),
                JudgeList = judgeContext.GetJudgeInCompetition(id.Value),
            };
            string CompName = compjudge.SelectedCompetition.CompetitionName;
            ViewData["CompName"] = CompName;
            ViewData["CompId"] = compjudge.SelectedCompetition.CompetitionID;
            int CompAOI = compjudge.SelectedCompetition.AreaInterestID;

            // check and remove judges already assigned to competition
            List<Judge> jList = judgeContext.GetJudgeAOI(CompAOI);
            foreach (Judge cj in compjudge.JudgeList)
            {
                for (int i = 0; i < jList.Count; i++)
                {
                    if (jList[i].JudgeID == cj.JudgeID)
                    {
                        jList.Remove(jList[i]);
                    }
                }
            }
            // if no more judges available for selected cometition 
            if (jList.Count == 0)
            {
                TempData["CompJudgeError"] = "No more judges available for " + CompName + "!";
                return RedirectToAction("CompetitionJudges", "Competition");
            }
            ViewData["JudgeList"] = jList;
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AssignJudge(CompetitionJudge competitionJudge)
        {
            CompetitionJudgeViewModel compjudge = new CompetitionJudgeViewModel
            {
                SelectedCompetition = competitionContext.GetCompetition(competitionJudge.CompetitionID),
                JudgeList = judgeContext.GetJudgeInCompetition(competitionJudge.CompetitionID),
            };
            string CompName = compjudge.SelectedCompetition.CompetitionName;
            ViewData["CompName"] = CompName;
            int CompId = compjudge.SelectedCompetition.CompetitionID;
            ViewData["CompId"] = CompId;
            int CompAOI = compjudge.SelectedCompetition.AreaInterestID;

            // check and remove judges already assigned to competition
            List<Judge> jList = judgeContext.GetJudgeAOI(CompAOI);
            foreach (Judge cj in compjudge.JudgeList)
            {
                for (int i = 0; i < jList.Count; i++)
                {
                    if (jList[i].JudgeID == cj.JudgeID)
                    {
                        jList.Remove(jList[i]);
                    }
                }
            }
            ViewData["JudgeList"] = jList;
            if (ModelState.IsValid)
            {
                // check if selected judge is involved in current or future competitions
                List<CompetitionJudge> cjList = compJudgeContext.GetAllCompetition(competitionJudge.JudgeID);
                foreach (CompetitionJudge cJudge in cjList)
                {
                    if (cJudge.CompetitionID != CompId) // exclude competition judge is going to be assigned to
                    {
                        Competition c = competitionContext.GetCompetition(cJudge.CompetitionID);
                        // using current date as reference
                        if (c.StartDate >= DateTime.Now && c.EndDate >= DateTime.Now)
                        {
                            // judge involved in other current or future competitions
                            Judge j = judgeContext.GetJudge(competitionJudge.JudgeID);
                            TempData["AssignJudgeError"] = j.JudgeName + " is involved in a current or future competition. Please select another judge.";
                            return View(competitionJudge);
                        }
                    }
                }
                compJudgeContext.AssignJudge(competitionJudge);
                TempData["CompJudgeSuccess"] = "New judge successfully assigned to " + CompName + "!";
                return RedirectToAction("CompetitionJudges", "Competition");
            }
            else
            {
                return View(competitionJudge);
            }
        }

        // to remove selected judge from competition
        public ActionResult RemoveJudge(int? id)
        {
            if ((HttpContext.Session.GetString("Role") == null) ||
            (HttpContext.Session.GetString("Role") != "admin"))
            {
                return RedirectToAction("index", "home");
            }
            if (id == null)
            {
                return RedirectToAction("CompetitionJudges", "Competition");
            }
            Judge judge = judgeContext.GetJudge(id.Value);
            if (judge == null)
            {
                TempData["CompJudgeError"] = "Error! No judge found.";
                return RedirectToAction("CompetitionJudges", "Competition");
            }
            compJudgeContext.RemoveCompJudge(id.Value);
            TempData["CompJudgeSuccess"] = "Judge removed from competition successfully!";
            return RedirectToAction("CompetitionJudges", "Competition");
        }
    }
}

WEB_Assignment_Team2/Views/Judge/AssignJudge.cshtml
@model WEB_Assignment_Team2.Models.CompetitionJudge

@{
    ViewData["Title"] = "Assign Judge";
}

<div id="comp-container" class="container">
    <h2>Assign New Judge for @ViewData["CompName"]</h2>
    <div style="color:orangered">@TempData["AssignJudgeError"]</div>
    <br />
    <form asp-action="AssignJudge" asp-controller="Judge">
        <fieldset class="FormContent form-container" style="margin-bottom: 20px;">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CompetitionID" class="control-label"></label>
                <input asp-for="CompetitionID" readonly class="form-control" value="@ViewData["CompID"]"/>
                <span asp-validation-for="CompetitionID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="JudgeID" class="control-label"></label>
                <span asp-validation-for="JudgeID" class="text-danger"></span>
                <select asp-for="JudgeID"
                        asp-items="@(new SelectList( @ViewData["JudgeList"]
                                    as List <Judge>, "JudgeID", "JudgeName"))"
                        class="form-control"></select>
            </div>
            <div class="row form-group">
                <div style="padding:15px;">
                    <input type="submit" value="Assign" class="btn btn-success" />
                </div>
                <div style="padding:15px;">
                    <input asp-action="CompetitionJudges" 
                           asp-controller="Competition" 
                           type="submit" value="Cancel" class="btn btn-danger" />
                </div>
            </div>
        </fieldset>
    </form>
</div>

WEB_Assignment_Team2/Views/Judge/View.cshtml
@model WEB_Assignment_Team2.Models.CompetitionJudgeViewModel
@{
    ViewData["Title"] = "View Judges";
}
<div class="container">
    @await Html.PartialAsync("~/Views/Shared/_CompetitionDetails.cshtml", Model.SelectedCompetition)
    <div style="border-style:none solid solid solid;border-width:1px;border-radius:0px 0px 10px 10px; min-height: 300px">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.JudgeList.FirstOrDefault().JudgeName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.JudgeList.FirstOrDefault().JudgeID)
                    </th>
                </tr>
            </thead>
            <tbody>
                @{
                    foreach (var item in Model.JudgeList)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Salutation) @Html.DisplayFor(modelItem => item.JudgeName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.JudgeID)
                            </td>
                        </tr>
                    }


                }
            </tbody>
        </table>
    </div>
</div>
<br />
@section Scripts{
    <script>
        $(".buttonCriteria a").css({ "padding": "2px 0px", "background-color": "white", "text-decoration": "none", "color": "#707070" })
        $("#btnJudges a").css({ "color": "blue" })
    </script>
}